from __future__ import annotations

from datetime import datetime
from types import TracebackType
from typing import Protocol, Self

from travel_agent.modules.itinerary.domain.models import ItineraryPlan, ItineraryVersionSummary


class ItineraryStore(Protocol):
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    async def trip_context(self, trip_id: str) -> dict[str, object] | None: ...
    async def actor_role(self, family_id: str, user_id: str) -> str | None: ...
    async def current(self, trip_id: str) -> ItineraryPlan | None: ...
    async def create(self, plan: ItineraryPlan, summary: str, request_id: str | None) -> None: ...
    async def update(
        self, plan: ItineraryPlan, expected_version: int, summary: str, request_id: str | None
    ) -> bool: ...
    async def versions(self, trip_id: str) -> tuple[ItineraryVersionSummary, ...]: ...
    async def commit(self) -> None: ...


class ItineraryStoreFactory(Protocol):
    def __call__(self) -> ItineraryStore: ...


class Clock(Protocol):
    def now(self) -> datetime: ...
